# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_ERg8m51l_eaoZKju9M-fDx47hjBdcj

***2025-2026 PYTHON PROGRAMLAMA DÖNEM SONU*** ***ÖDEVİ***

***Veri Yapıları ve Temel Mantık***
"""

import random

# 1. Değişkenler ve Tipler
ad_soyad = "Ahmet Yılmaz"  # string
aylik_ucret = 550.50        # float
sadakat_ayi = 25           # int
aktif_mi = True            # boolean

# 2. Liste ve Sözlük Kullanımı
hizmetler = ["Fiber İnternet", "TV+ Paketi", "Sabit Telefon", "Bulut Depolama", "Güvenlik Paketi"]

musteri_bilgileri = {
    "ad_soyad": ad_soyad,
    "aylik_ucret": aylik_ucret,
    "sadakat_ayi": sadakat_ayi,
    "aktif_mi": aktif_mi,
    "alinan_hizmetler": hizmetler
}

# 3. Koşullu İfadeler (If-Else)
if musteri_bilgileri["aylik_ucret"] > 500 or musteri_bilgileri["sadakat_ayi"] > 24:
    print("VIP Müşteri: İndirim Tanımla")
else:
    print("Standart Müşteri")

# 4. String Operasyonları ve Random
ad_buyuk = musteri_bilgileri["ad_soyad"].upper()
rastgele_sayi = random.randint(1000, 9999)
customerID = f"IST-2026-{rastgele_sayi}"

print(f"Müşteri: {ad_buyuk} | ID: {customerID}")

"""***Fonksiyonlar, Döngüler ve Yapılar***"""

import math
from datetime import datetime

# 1. Döngüler ve Listeler (#Müşteri Listesi Oluşturma)
musteriler_listesi = [
    {"ad": "Ali", "ucret": 400, "ay": 10, "churn": False},
    {"ad": "Ayşe", "ucret": 600, "ay": 30, "churn": False},
    {"ad": "Mehmet", "ucret": 300, "ay": 5, "churn": True},
    {"ad": "Fatma", "ucret": 750, "ay": 12, "churn": False},
    {"ad": "Can", "ucret": 450, "ay": 26, "churn": False}
]

# 2. Fonksiyon Tanımlama (#KDV Hesaplama Fonksiyonu)
def tutar_hesapla(aylik_ucret):
    kdv_dahil = aylik_ucret * 1.20 # %20 KDV ekleme
    return kdv_dahil # #Değer Döndürme

# 3. Kütüphane Kullanımı ve Döngü (#Müşteri Analizi)
print("--- FATURA DETAYLARI ---")
for musteri in musteriler_listesi: # #Döngü Kullanımı
    net_tutar = tutar_hesapla(musteri["ucret"])
    son_tutar = math.ceil(net_tutar) # #Math Kütüphanesi ile Yukarı Yuvarlama

    # Churn Risk Analizi
    status = "RİSKLİ" if musteri["ay"] < 6 or musteri["churn"] else "GÜVENLİ"

    print(f"Müşteri: {musteri['ad']} | Fatura: {son_tutar} TL | Durum: {status}")

# Bugünün Tarihi (#Datetime Kütüphanesi)
bugun = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
print(f"\nFatura Kesim Tarihi: {bugun}")

# 4. Hata Denetimi ve Set Kullanımı (#Benzersiz Hizmetler)
tum_hizmetler = ["İnternet", "TV", "İnternet", "Telefon", "TV", "Bulut"]
benzersiz_hizmetler = set(tum_hizmetler) # #Set Kullanımı ile Tekrarları Silme
print(f"Sunulan Benzersiz Hizmetler: {benzersiz_hizmetler}")